eureka:
  client:
    service-url:
      defaultZone:  http://localhost:7001/eureka
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka-server
server:
  port: 7001
